// <auto-generated />
using System;
using EventOrchestrationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventOrchestrationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629173521_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventOrchestrationService.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("ИД бронирования");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата создания бронирования");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasComment("ИД события");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата обработки события");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasComment("Статус бронирования:\r\n1 - В обработке (Pending)\r\n2 - Подтверждено (Confirmed)\r\n3 - Отклонено (Rejected)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Bookings", "public");
                });

            modelBuilder.Entity("EventOrchestrationService.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("ИД события");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasComment("Доступное количество мест на событие");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Описание события");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата окончания события");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата начала события");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Название события");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasComment("Общее количество мест на событие");

                    b.HasKey("Id");

                    b.ToTable("Events", "public");
                });

            modelBuilder.Entity("EventOrchestrationService.Entities.Booking", b =>
                {
                    b.HasOne("EventOrchestrationService.Entities.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventOrchestrationService.Entities.Event", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
