// <auto-generated />
using System;
using EventOrchestrationService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventOrchestrationService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730211557_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventOrchestrationService.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("ИД бронирования");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата создания бронирования");

                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasComment("ИД события");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата обработки события");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasComment("Статус бронирования:\r\n1 - В обработке (Pending)\r\n2 - Подтверждено (Confirmed)\r\n3 - Отклонено (Rejected)\r\n3 - Отменено (Cancelled)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasComment("ИД пользователя");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", "public");
                });

            modelBuilder.Entity("EventOrchestrationService.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("ИД события");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasComment("Доступное количество мест на событие");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Описание события");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата окончания события");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasComment("Версия строки для оптимистической блокировки");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Дата начала события");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Название события");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasComment("Общее количество мест на событие");

                    b.HasKey("Id");

                    b.ToTable("Events", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 10,
                            Description = "Description1",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Title1",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 10,
                            Description = "Description2",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Title2",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 10,
                            Description = "Description3",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Title3",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 10,
                            Description = "Description4",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "ABC_Title4",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 10,
                            Description = "Description5",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "abc_Title5",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 10,
                            Description = "Description6",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "AbC_Title6",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 10,
                            Description = "Description7",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Title7",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 10,
                            Description = "Description8",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Title8",
                            TotalSeats = 10
                        },
                        new
                        {
                            Id = 9,
                            AvailableSeats = 10,
                            Description = "Description9",
                            EndAt = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = 0u,
                            StartAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Title9",
                            TotalSeats = 10
                        });
                });

            modelBuilder.Entity("EventOrchestrationService.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("ИД пользователя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Хэш пароля");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasComment("Роль Пользователя:\r\n1 - Пользователь (User)\r\n2 - Администратор (Admin)");

                    b.HasKey("Id");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("EventOrchestrationService.Domain.Entities.Booking", b =>
                {
                    b.HasOne("EventOrchestrationService.Domain.Entities.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventOrchestrationService.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventOrchestrationService.Domain.Entities.Event", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("EventOrchestrationService.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
